### ISSUE TITLE
Why are we doing everything in the develop branch?

### ISSUE THREAD

**Issue by corcra** [ahli-chil/chil-website#101]
Not urgent, just curious

**Comment by tompollard** [comment]
@corcra I thought that we had now moved to the main branch? @getsarker was working on the dev branch last year to avoid stepping on our toes too much while he implemented some large-ish changes, but I thought that he had merged everything with main? Not checked, so I might be wrong.

**Comment by corcra** [comment]
Oh good point. Yes these can be auto-merged. Think we should just merge+delete the develop branch so.
